name: Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Execute OCI ARM Check
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_KEY_CONTENT: ${{ secrets.OCI_KEY_CONTENT }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_MAX_INSTANCES: 1
          OCI_SHAPE: VM.Standard.A1.Flex
          OCI_OCPUS: ${{ secrets.OCI_OCI_ARM_CAPACITY }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_OCI_ARM_MEMORY }}
        run: php index.php
